### PR TITLE
README: translation

### PR DESCRIPTION
**Pull request by lex111**
@lgiordani please give me edit access to this repository, so I do not create a PR afterwards.

### CODE REVIEW

**Comment by lgiordani** [comment]
Sorry, I was sure I already set it up. Today I noticed that you don't have the 2FA set up, however. WOuld you mind setting it up? I'd definitely prefer to know that everyone has write access cannot be compromised too easily. Thanks!

**Comment by lex111** [comment]
Make sense. Done :heavy_check_mark:

**Comment by lgiordani** [comment]
@lex111 I believe you can write this repo now (now sure, it's the first time I set up a collaboration on GH). Can you try to merge your own PR just to verify it?

**Comment by lex111** [comment]
Now I can do it, thank you! :100:

**Pull request merged**
